steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app:$COMMIT_SHA
      - -t
      - europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app:latest
      - .

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - suivi-finance
      - --image=europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app:latest
      - --region=europe-west1
      - --platform=managed
      - --project=suivi-finance-472610

images:
  - 'europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/suivi-finance-472610/suivi-finance/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
